### ISSUE TITLE
Rancher Kubernetes gives invalid scheme ""

### ISSUE THREAD

**Issue by ls-yann-david** [objectpartners/rancher-ecr-credentials#12]
I have a kubernetes environment and I'd like to use this to login to ECR but using this:

```
apiVersion: v1
kind: Pod
metadata:
  name: "ecr"
  namespace: "default"
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.create_agent: "true"
    io.rancher.container.agent.role: "environment"
spec:
  containers:
    - name: "ecr-credential-fetcher"
      image: "objectpartners/rancher-ecr-credentials:1.1.0"
      env:
        - name: "AWS_REGION"
          value: "us-east-1"
```

I always have invalid scheme "". Isn't it suposed to fetch the CATTLE_URL and KEY/SECRET with those label on?
