### ISSUE TITLE
Can't pull images from ECR

### ISSUE THREAD

**Issue by predmijat** [objectpartners/rancher-ecr-credentials#22]
Hi,

I've added a service in my `docker-compose.yml`:

```
ECRCredentials:
  environment:
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: XXXXXXXXXXXXXXXXXXXX
    AWS_SECRET_ACCESS_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  tty: true
  image: objectpartners/rancher-ecr-credentials
  stdin_open: true
```

Container is running fine:
```
2/10/2017 11:55:12 AMUpdating ECR Credentials
2/10/2017 11:55:13 AMReturned from AWS GetAuthorizationToken call successfully
2/10/2017 11:55:13 AMLooking for configured registry for host x.dkr.ecr.us-east-1.amazonaws.com
2/10/2017 11:55:13 AMSuccessfully updated credentials _ for registry _; registry address: x.dkr.ecr.us-east-1.amazonaws.com
2/10/2017 5:03:53 PMUpdating ECR Credentials
2/10/2017 5:03:53 PMReturned from AWS GetAuthorizationToken call successfully
2/10/2017 5:03:53 PMLooking for configured registry for host x.dkr.ecr.us-east-1.amazonaws.com
2/10/2017 5:03:53 PMSuccessfully updated credentials _ for registry _; registry address: x.dkr.ecr.us-east-1.amazonaws.com
...
```

But if I try to upgrade one of the containers by providing new image URL, I get this:
`Expected state running but got error: Image [x.dkr.ecr.us-east-1.amazonaws.com/loci/my_image:version] failed to pull: Download complete`.

Then I figured that the image I'm trying to update is running on host-2, while `rancher-ecr-credentials` is running on host-1 - should I run `rancher-ecr-credentials` on each host or valid login is somehow distributed via Rancher?

Then I've SSHed to the Rancher host `rancher-ecr-credentials` is running on but even there I can't pull the image:
`unauthorized: authentication required`

Thanks!

**Comment by johnrengelman** [comment]
No, the updater calls into the Rancher API and updates the credentials for an already configured registry you have there. Have you configured the ECR in the Rancher Registry UI for the environment you are running this in?

The first error appears to be some other issue since you don't get an unauthorized error, so that seems to be that docker is able to log into the registry. Not sure what to do there. Are you doing something custom with the docker engine install/options?

The second error is expected as the registry is configured via Rancher to the agent process. It does not execute a log in on the host machine docker engine.

**Comment by predmijat** [comment]
Must've missed the notification, sorry for the late response.
Yes, there's a configured registry in the environment `rancher-ecr-credentials` is running in.
Nothing funky with Docker engine, it's default AMI, provisioned by Rancher (Ubuntu).

**Comment by arsdehnel** [comment]
I'm getting the same thing 

```
(Failed to allocate instance [container:1i116]: Bad instance [container:1i116] in state [error]: Image [<ecr image/tag url>] failed to pull: Pulling repository <ecr image/tag url>) 
```

this is my config:

```
ecr-updater:
  environment:
    AWS_ACCESS_KEY_ID: <key>
    AWS_REGION: us-west-2
    AWS_SECRET_ACCESS_KEY: <key>
    AUTO_CREATE: true
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  tty: true
  image: objectpartners/rancher-ecr-credentials:1.2.0
  stdin_open: true
```

I agree with you @johnrengelman that the credential lookup seems to be working fine but then the repo pull is not.  

Not sure if it is related or not but I also had a problem with the AUTO_CREATE option.  It seems like it worked to create the registry but I get an error in the logs from it:

```
3/27/2017 4:43:00 PM2017/03/27 21:43:00 [main] Updating ECR Credentials
3/27/2017 4:43:00 PM2017/03/27 21:43:00 [healthcheck] Starting Healthcheck listener at :8080/ping
3/27/2017 4:43:00 PM2017/03/27 21:43:00 [updateEcr] Returned from AWS GetAuthorizationToken call successfully
3/27/2017 4:43:00 PM2017/03/27 21:43:00 [processToken <ecr url>] Looking for configured registry for host: <ecr url>
3/27/2017 4:43:00 PM2017/03/27 21:43:00 [processToken <ecr url>] Automatically creating registry for host: <ecr url>
3/27/2017 4:43:00 PM2017/03/27 21:43:00 [processToken <ecr url>] Error creating registry credential for host: <ecr url>, Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=email, code=MissingRequired, baseType=error] from [http://rancher1.biw-services.com/v1/registrycredentials]
```

But then it actually _is_ created when I go to the UI and look at the data in the API.  But maybe something about the Rancher Registry API changed somewhere along the line and they are related? Or maybe they are totally unrelated, too new to Rancher to really know for sure.
