### ISSUE TITLE
Failed to update registry credential 1c18 Error

### ISSUE THREAD

**Issue by bobjana** [objectpartners/rancher-ecr-credentials#5]
Rancher: 1.0

Log:
_Checking: https://#########.dkr.ecr.us-east-1.amazonaws.com
Checking registry: #########.dkr.ecr.us-east-1.amazonaws.com against: #########.dkr.ecr.us-east-1.amazonaws.com
Failed to update registry credential 1c18, Resource type [registryCredential] is not updatable_

Not entirely sure whether it's a setting I need to configure on the ecr side or a parameter I'm missing/misconfigured on ecr-container.

Please advise

**Comment by johnrengelman** [comment]
Sounds like a change that they made in the 1.0 release.

**Comment by johnrengelman** [comment]
@bobjana Not sure what the problem might be here, but I just updated one of my clusters that is using this same service and I'm not having any issues.
Are you still experiencing problems?

**Comment by smazurov** [comment]
I had this issue running v1.0.0 of this image, updating to v1.0.1 fixed it.

**Comment by bobjana** [comment]
Went with comment above and upgraded to 1.0.1

Now I'm getting a different error:

_Failed to create rancher client: Get : unsupported protocol scheme ""
Error updating ECR, Get : unsupported protocol scheme ""_

Also note that I installed it via rancher catalog (which has the old 1.0.0 version), upgraded it to 1.0.1 and started it from within rancher.

**Comment by smazurov** [comment]
you probably lost the labels - there is one that sets the right env vars which allows you to connect to rancher api. 

Start over, remove the service you added from catalog and create a new stack with this `docker-compose.yml`:

```yaml
ecr-updater:
  environment:
    AWS_ACCESS_KEY_ID: ${aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: ${aws_secret_access_key}
    AWS_REGION: ${aws_region}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  tty: true
  image: objectpartners/rancher-ecr-credentials:1.0.1
  stdin_open: true
```
